### ISSUE TITLE
[Task] Shipment | Packing List "Total Pallet" Change Formula

### ISSUE THREAD

**Issue by Pei4** [luminatechnology/Tomofun_23R1#13]
# Scenario
- The current formula for "Total Pallet" doesn't fit users' actual scenario
# Spec
- Adjust "Total Pallet" formula as follows
  - Total Pallet = RoundUp( SOPackageDetailEx.UsrTotalCartons / Stock Item.Attribute ‘Attr ID’ )
      - If SOShipment.ShipVia = ‘AIR’ and SOShipmentAddress.CountryID = “CN/TW/HK/AU/NZ/SG/US/CA/MX/JP/UK” then Attr ID = ‘PLTAIRUS’ (Cartons per Pallet via AIR to US)
      - If SOShipment.ShipVia = ‘OCEAN’ and SOShipmentAddress.CountryID = “CN/TW/HK/AU/NZ/SG/US/CA/MX/JP/UK” then Attr ID = ‘PLTSEAUS’ (Cartons per Pallet via SEA to US)
      - If SOShipment.ShipVia = ‘AIR’ and SOShipmentAddress.CountryID = “BE/DE/ES/FR/IT/NL/SE” then Attr ID = ‘PLTAIREU’ (Cartons per Pallet via AIR to EU)
      - If SOShipment.ShipVia = ‘OCEAN’ and SOShipmentAddress.CountryID = “BE/DE/ES/FR/IT/NL/SE” then Attr ID = ‘PLTSEAEU’ (Cartons per Pallet via SEA to EU)
# Ref
- [Packing List Report v1.5](https://1drv.ms/w/s!AhdB9H8nvN7jhp5tHy2B8MaeHCGeVA?e=F4yYJL)

**Comment by Pei4** [comment]
@JeffJave Please help adjust the "Total pallet" formula.
It is expected to be updated to PRD together with #12

**Comment by JeffJave** [comment]
Hi @Pei4,

I've modified the total pallet calculation conditions according to the enhanced spec, and Wayne will merge and update them into the sandbox tomorrow after he completes the task.
