### ISSUE TITLE
Shipment | Restore the Old Version of Packing List As a New Report

### ISSUE THREAD

**Issue by Pei4** [luminatechnology/Tomofun_23R1#26]
# Scenario
- User wants to see the historical Packing List, which can not be rendered in the current version of Packing List

# Spec
- Please add a new report titled "Print Packing List (Old)"
  - Restore from Packing List v1.1
![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/580afb14-cd7f-4b65-ac5d-913cec937941)
# Remark
- [x] Cancel "Hidden" for user-defined field `Pallet Size` and `Pallet Size 2` @Pei4

**Comment by JeffJave** [comment]
Hi @Pei4,

I've published the old version we decided to sand box, could you please help me check what is the difference between them.
Thanks a lot.

**Comment by Pei4** [comment]
@JeffJave 
Thanks a lot for your prompt update.
The content fits our expectations well, but the stamp image has to be updated.
Please help update the stamp image as below:
- [Image link](https://1drv.ms/i/s!AhdB9H8nvN7jhf9VJT--VIEPkzT7Xw?e=aFGyl6)

**Comment by JeffJave** [comment]
Hi @Pei4,

The image has been updated with differences in resolution and edge thickness.

**Comment by Pei4** [comment]
Hi @JeffJave 
Some of the columns didn't show up after the image was updated.
Please help bring back these columns, thx~
![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/62815171-61e5-4bdc-9f68-f54d4c989d19)

**Comment by JeffJave** [comment]
Hi @Pei4,

Could I know which test sample you chose?

**Comment by Pei4** [comment]
> Hi @Pei4,
> 
> Could I know which test sample you chose?

@JeffJave Please see [TSH220096](http://44.238.146.140/Sandbox/(W(9))/Main?CompanyID=TW&ScreenId=SO302000&ShipmentNbr=TSH220096) for example

**Comment by JeffJave** [comment]
Hi @Pei4,

After checking the report, those fields are empty in shipment packages.
![Screenshot 2024-01-18 at 3 47 57 PM](https://github.com/luminatechnology/Tomofun_23R1/assets/22957811/46c68031-fc90-4814-97fa-2b709e759a8c)

**Comment by Pei4** [comment]
@JeffJave The report looks quite fine now, thank you!
I will schedule the release day together with #20
