### ISSUE TITLE
SQL View for Operation CR

### ISSUE THREAD

**Issue by Pei4** [luminatechnology/Tomofun_23R1#39]
# Scenario
- There is a lot of data across different tenants that need to be joined for this project (v1.1.0~v1.4.0)
# Spec
- Join the following tables and columns:
  - Shipment
    - `SOShipment.ShipmentNbr`
  - TW SO: from `SOShipLine.OrigOrderNbr`
    - `SOOrder.OrderNbr`
    - `SOOrder.OrderQty`
    - `SOOrder.CuryOrderTotal`
  - Vendor PO: from `SOLineSplit.RefNoteID`
    - `POOrder.OrderNbr`
    - `POOrder.OrderQty`
    - `POOrder.CuryOrderTotal`
  - Vendor PR: from `POOrderPOReceipt.ReceiptNbr`
    - `POReceipt.ReceiptNbr`
    - `POReceipt.OrderQty`
    - `POReceiptLine.InventoryID` 
    - `POReceiptLine.SiteID`
  - Foreign PO: from `SOOrder.CustomerOrderNbr`
    - `POOrder.OrderNbr`
    - `POOrder.OrderQty`
    - `POOrder.CuryOrderTotal`
  - Foreign PR: from `POOrderPOReceipt.ReceiptNbr`
    - `POReceipt.ReceiptNbr`
    - `POReceipt.OrderQty`
    - `POReceiptLine.InventoryID` 
    - `POReceiptLine.SiteID`
  - Transfer PR: from `POReciptLine.SOShipmentNbr`
    - `POReceipt.ReceiptNbr`
    - `POReceipt.OrderQty`
    - `POReceiptLine.InventoryID` 
    - `POReceiptLine.SiteID`
    ![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/0c403c21-e390-413a-8ea0-a8e3c1772843)
   ![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/9f9c2efe-4204-46fb-9638-efebd276a6b1)
    ![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/70bc0900-512d-49cb-980a-174ea5960b1b)
    ![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/d30b6044-0914-4037-bb53-996552daf2fe)
- If any of `Foreign PO`, `Foreign PR`, or `Transfer PR` is null, then return empty

**Comment by WayneLin29** [comment]
SQL ViewName: v_ShipmentToSO_VendorAndICAndTRPOPR

**Comment by WayneLin29** [comment]
v_ShipmentToSO
v_ShipmentToSO_VendorAndICAndTRPOPR

**Comment by Pei4** [comment]
^ Note: Split the SQL view due to multiple Shipment lines scenario
(causing duplication when joining PO Receipt line)
