### ISSUE TITLE
Shopify API Interface | Skip Rules

### ISSUE THREAD

**Issue by Pei4** [luminatechnology/Tomofun_23R1#41]
# Scenario
Some of the Shopify orders from API weren't processed  
- Skipped JSON sample in TW: [Skipped JSON.json](https://github.com/luminatechnology/Tomofun_23R1/files/14940618/Skipped.JSON.json) (Order ID: 5554292719956)
# Spec
Please help check out the skip rules of Shopify API Interface
# Ref
- Shopify-related issues reported by users: [Error message_reply_240402.xlsx](https://github.com/luminatechnology/Tomofun_23R1/files/14940627/Error.message_reply_240402.xlsx)

**Comment by WayneLin29** [comment]
The follow conditions will cause data to skipped:
1.financial_status != 'paid'
2.[Existting Order] != null && financial_status == 'paid' && fulfillment_status is empty
3.[Existting Order] != null && [Existting Order].Status != 'N' && fulfillment_status == 'FULFILLED'
***[Existting Order] refers to shopfy order exists in Systmen**

**Comment by Pei4** [comment]
Hi @WayneLin29 
These 2 JSON data didn't fit the skip conditions but still be skipped.
- ES: [Skipped JSON_5783380296020.json](https://github.com/luminatechnology/Tomofun_23R1/files/14957195/Skipped.JSON_5783380296020.json) (Sequence: 1682504)
- NL: [Skipped JSON_5711984853336.json](https://github.com/luminatechnology/Tomofun_23R1/files/14957228/Skipped.JSON_5711984853336.json) (Sequence: 1682505)

![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/28e535b7-9da6-4850-9982-07ab33ca4103)

**Comment by Pei4** [comment]
Update to https://github.com/luminatechnology/Tomofun_23R1/issues/41#issuecomment-2051480896:
- Reason: `Error converting value {null} to type 'System.DateTime'. Path 'customer.accepts_marketing_updated_at', line 1, position 5091.`
- Solution: Wayne will update the code
