### ISSUE TITLE
Create Dev Environment For Internal Testing

### ISSUE THREAD

**Issue by Pei4** [luminatechnology/Tomofun_23R1#43]
# Scenario
- We have multiple features that are developing and UAT testing simultaneously, which causes difficult versioning.
# Spec
@JeffJave 
- [x] Please help open a new instance in 01 server
- [x] Please authorize Wayne to access the server

@WayneLin29 
- [x] Please create a Dev tenant in 01 server
- [x] Please restore Tomofun's tenants in Dev tenant
  - [TW Snapshot](https://1drv.ms/u/s!AhTQRpjKPT2MlUcKLG2JyVRGjJrx?e=chsGW6)
  - [US Snapshot](https://1drv.ms/u/s!AhTQRpjKPT2MlH4K4B4e0ncdM5at?e=QFbiFN)
  - [JP Snapshot](https://1drv.ms/u/s!AhTQRpjKPT2MlUprBoZSkxXOAD5P?e=5fue1Q)
  - EU Snapshot (TBD)

**Comment by Pei4** [comment]
@JeffJave Would it be available for you to do this issue at the end of this Wednesday?

**Comment by JeffJave** [comment]
Hi @Pei4,

Sorry, do you mean I finish all the steps or just my part.

**Comment by Pei4** [comment]
@JeffJave Only your part~

**Comment by JeffJave** [comment]
Hi @Pei4,

Oh~~~ got it, I've given the access information to Wayne and turn the server on..

**Comment by Pei4** [comment]
@WayneLin29 Please help create the Dev environment before we develop #42 
Besides, is it possible to resume Sandbox's version back to v1.1.0?

**Comment by Pei4** [comment]
Note: Create Dev environment after finish #42

**Comment by Pei4** [comment]
https://dev01.clouderp.com.tw/Tomofun
(Still cannot upload US tenant)
