### ISSUE TITLE
Packing List | Modify the Spacing to Show Completed Container No.

### ISSUE THREAD

**Issue by Pei4** [luminatechnology/Tomofun_23R1#46]
# Scenario
- The string will exceed the column when users key in multiple Container No. for multiple package lines
  ![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/7adb7a6e-ba55-45e9-bf2a-746a7002b2b2)

# Spec
- Please modify the column size and the spacing of the report to show the completed information in single page of Packing List
- Sample data
  - Container No.: MUTD234567, MUTG1223456, MUTD987654, MUTD987655, MUTD987657
  - Package: 5 lines  

![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/f4d5deb1-c378-4be3-83d8-8cf28ecaef1f)

**Comment by JeffJave** [comment]
Hi @Pei4,

I've revised the report in sand box, could you please help with checking when you're available.
Thank you.
![Uploading Screenshot 2024-04-23 at 1.21.19 PM.png…]()

**Comment by Pei4** [comment]
@JeffJave The result is perfect!
Thank you very much 🙌
