### ISSUE TITLE
[Task] Shipment | Package Tab Add Columns & Enhancement

### ISSUE THREAD

**Issue by Pei4** [luminatechnology/Tomofun_23R1#5]
# Scenario
- Users need more flexibility to edit the length, width, and height of the pallet size

# Spec
## Tomofun Preference
- Add "Tomofun Preference" form under Customization Module
  - Add "Shipment" Section
    - Add 3 decimal(10,2) columns for users to maintain the default length, width and height
        ![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/4eb45fe5-7a83-48ed-ab5e-d6f79d18c994)
- Will only be used in TW tenant (Hide in other tenants' sitemap)
## Shipment - Package Tab
- Add the following columns, all in decimal(10,2) format → Get default value from Tomofun Reference
  - Pallet Length
  - Pallet Width
  - Pallet Height
- Add rule for "Pallet Size (CM)" column `PALLETSIZE`
  - If `PalletLength` / `PalletWidth` / `PalletHeight` is changed, Then update `PALLETSIZE`
  - `PALLETSIZE` = `PalletLength`x`PalletWidth`x`PalletHeight` CM
      - Hide 0 after decimal point
![image](https://github.com/luminatechnology/Tomofun_23R1/assets/40812695/c7025c3c-bf33-46ef-abe0-0ae93f81d493)
- Change the formula for "Volume (CBM)"
  - ROUND(Sum up all lines' (`PalletLength` x `PalletWidth` x `PalletHeight` / 1,000,000 x `UsrTotalPallet`), 2)
  - Recalculate while any of the above fields change

# Ref
- Past spec: [Packing List Report v1.4](https://1drv.ms/w/s!AhdB9H8nvN7jhoVq2IJOt0lFta1pfQ?e=3QYUCg)

**Comment by Pei4** [comment]
@JeffJave 
Please help develop this enhancement by this Friday in Sandbox.
Feel free to let me know if you have any problem with the spec or the schedule, thank you!

**Comment by Pei4** [comment]
@JeffJave The spec has been updated (Tomofun Preference part) 🙏

**Comment by JeffJave** [comment]
Hi @Pei4,

I've finished the enhancements and published to UAT, please help with testing when you're available.
Thank you.
